name = "liveband-media"
main = "media-worker.js"
compatibility_date = "2025-01-01"
account_id = "677b2fbb69edb3bc8e8839ae5feeb2cb"

[[routes]]
pattern = "www.liveband.ru/band/*/images/*"
zone_name = "liveband.ru"

[[routes]]
pattern = "www.liveband.ru/band/*/music/*.mp3"
zone_name = "liveband.ru"

[[routes]]
pattern = "www.liveband.ru/club/*/images/*"
zone_name = "liveband.ru"
